
//economic and management Sciences
const course1 = new Course({
  name : "accounting science",
  code: "BCom",
  years: "3 years",
  stream: "economic and management sciences",
  school:{
    name:["UP"],
    aps:[34]
  },
  career:["tax advisor","financial manager","auditor"],
  scarcity:4
});

const course2 = new Course({
  name : "investment management",
  code: "BCom",
  years: "3 years",
  stream: "economic and management sciences",
  school:{
    name:["UP"],
    aps:[34]
  },
  career:["investment analyst","risk manager","fund manager","financial advisor"],
  scarcity:4
});

const course3 = new Course({
  name : "financial science",
  code: "BCom",
  years: "3 years",
  stream: "economic and management sciences",
  school:{
    name:["UP"],
    aps:[32]
  },
  career:["cost accountant","tax auditor","financial accountant"],
  scarcity:4
});

const course4 = new Course({
  name : "econometrics",
  code: "BCom",
  years: "3 years",
  stream: "economic and management sciences",
  school:{
    name:["UP"],
    aps:[32]
  },
  career:["analyst","trader","consultants"],
  scarcity:4
});

const course5 = new Course({
  name : "economics",
  code: "BCom",
  years: "3 years",
  stream: "economic and management sciences",
  school:{
    name:["UP"],
    aps:[32]
  },
  career:["analyst","consultants","academics"],
  scarcity:4
});

const course6 = new Course({
  name : "statistics and data science",
  code: "BCom",
  years: "3 years",
  stream: "economic and management sciences",
  school:{
    name:["UP"],
    aps:[32]
  },
  career:["data scientist","statistical analyst","lecturer"],
  scarcity:4
});

const course7 = new Course({
  name : "informatics",
  code: "BCom",
  years: "3 years",
  stream: "economic and management sciences",
  school:{
    name:["UP"],
    aps:[30]
  },
  career:["IT manager","software support service","business analyst"],
  scarcity:4
});

const course8 = new Course({
  name : "agribusiness management",
  code: "BCom",
  years: "3 years",
  stream: "economic and management sciences",
  school:{
    name:["UP"],
    aps:[30]
  },
  career:["agricultural economics","agribusiness managers","project manager"],
  scarcity:4
});

const course9 = new Course({
  name : "bcom",
  code: "BCom",
  years: "3 years",
  stream: "economic and management sciences",
  school:{
    name:["UP"],
    aps:[30]
  },
  career:["does not lead to a specific career"],
  scarcity:4
});

const course10 = new Course({
  name : "business management",
  code: "BCom",
  years: "3 years",
  stream: "economic and management sciences",
  school:{
    name:["UP"],
    aps:[30]
  },
  career:["teachers","human resource manager","manager"],
  scarcity:4
});

const course11 = new Course({
  name : "supply chain management",
  code: "BCom",
  years: "3 years",
  stream: "economic and management sciences",
  school:{
    name:["UP"],
    aps:[30]
  },
  career:["supply manager","production manager","operation manager"],
  scarcity:4
});

const course12 = new Course({
  name : "marketing management",
  code: "BCom",
  years: "3 years",
  stream: "economic and management sciences",
  school:{
    name:["UP"],
    aps:[30]
  },
  career:["strategic management","product management","advertising management"],
  scarcity:4
});

const course13 = new Course({
  name : "human resource management",
  code: "BCom",
  years: "3 years",
  stream: "economic and management sciences",
  school:{
    name:["UP"],
    aps:[30]
  },
  career:["HR practitioner","HR consultants","mediators"],
  scarcity:4
});


//Engineering
const course14 = new Course({
  name : "industrial engineering",
  code: "BEng",
  years: "4 years",
  stream: "Engineering",
  school:{
    name:["UP"],
    aps:[35]
  },
  career:["industrial engineer"],
  scarcity:4
});

const course15 = new Course({
  name : "chemical engineering",
  code: "BEng",
  years: "4 years",
  stream: "Engineering",
  school:{
    name:["UP"],
    aps:[35]
  },
  career:["chemical engineer"],
  scarcity:4
});
const course16 = new Course({
  name : "civil engineering",
  code: "BEng",
  years: "4 years",
  stream: "Engineering",
  school:{
    name:["UP"],
    aps:[35]
  },
  career:["civil engineer"],
  scarcity:4
});

const course17 = new Course({
  name : "electrical engineering",
  code: "BEng",
  years: "4 years",
  stream: "Engineering",
  school:{
    name:["UP"],
    aps:[35]
  },
  career:["electrical engineer"],
  scarcity:4
});

const course18 = new Course({
  name : "electrical engineering",
  code: "BEng",
  years: "4 years",
  stream: "Engineering",
  school:{
    name:["UP"],
    aps:[35]
  },
  career:["electrical engineer"],
  scarcity:4
});

const course19 = new Course({
  name : "electronic engineering",
  code: "BEng",
  years: "4 years",
  stream: "Engineering",
  school:{
    name:["UP"],
    aps:[35]
  },
  career:["electronic engineer"],
  scarcity:4
});

const course20 = new Course({
  name : "mechanical engineering",
  code: "BEng",
  years: "4 years",
  stream: "Engineering",
  school:{
    name:["UP"],
    aps:[35]
  },
  career:["mechanical engineer","aeronautical engineer"],
  scarcity:4
});

const course21 = new Course({
  name : "metallurgical engineering",
  code: "BEng",
  years: "4 years",
  stream: "Engineering",
  school:{
    name:["UP"],
    aps:[35]
  },
  career:["metallurgical engineer"],
  scarcity:4
});

const course22 = new Course({
  name : "mining engineering",
  code: "BEng",
  years: "4 years",
  stream: "Engineering",
  school:{
    name:["UP"],
    aps:[35]
  },
  career:["mining engineer"],
  scarcity:4
});

const course23 = new Course({
  name : "computer engineering",
  code: "BEng",
  years: "4 years",
  stream: "Engineering",
  school:{
    name:["UP"],
    aps:[35]
  },
  career:["computer engineer"],
  scarcity:4
});

//built environment

const course24 = new Course({
  name : "architecture",
  code: "BSc",
  years: "3 years",
  stream: "built environment",
  school:{
    name:["UP"],
    aps:[27]
  },
  career:["architecture"],
  scarcity:4
});

const course25 = new Course({
  name : "construction management",
  code: "BSc",
  years: "3 years",
  stream: "built environment",
  school:{
    name:["UP"],
    aps:[30]
  },
  career:["construction site management"],
  scarcity:4
});

const course26 = new Course({
  name : "real estate",
  code: "BSc",
  years: "3 years",
  stream: "built environment",
  school:{
    name:["UP"],
    aps:[30]
  },
  career:["property investment","property management"],
  scarcity:4
});

const course27 = new Course({
  name : "quantity surveying",
  code: "BSc",
  years: "3 years",
  stream: "built environment",
  school:{
    name:["UP"],
    aps:[30]
  },
  career:["quantity surveyor"],
  scarcity:4
});
